### ISSUE TITLE
Add Settings Menu

### ISSUE THREAD

**Issue by ItsCentric** [ItsCentric/music-wizard#1]
Add a settings menu for the user to customize preferences and settings tied to their account. These preferences should be persisted to the database under the **User** collection, in the `preferences` field, as to be retrieved both by the Discord bot and the website.

### List of Preferences/Settings

- Preferred default time range
- Profile privacy
  - Public/private profile (setting to private shows nothing to un-whitelisted users)
  - Profile black/whitelist
  - Top items public/private (setting to private does not display top tracks/artists to un-whitelisted users)
  - Top items black/whitelist

### Tasks

- [x] Layout structure of menu
- [x] Add form to change preferences and settings
- [x] Persist form to the database
- [x] Add button to delete account and delete it from the database
