### ISSUE TITLE
Add Music Player

### ISSUE THREAD

**Issue by ItsCentric** [ItsCentric/music-wizard#12]
Add a music player page that incorporates a music player from all supported third party services

### Features
- Can skip to the next or previous track
- Supports all supported third party services
- Automatically detects the current service
- Can pause the current track
- Add the current track to the library of the service account the user is currently streaming from (include playlists)
- Scrub through the current track using the progress bar
- Can start a group session with other users
- Can shuffle the current queue
- Can repeat the current track or queue
- Can view the current queue

### Music Player Information
- Current track name
- Current track artist
- Current track album
- Current track cover
- Duration
- Current track lyrics through Genius
- Next track in the queue when there is 10 seconds or less left in the current track

### Tasks
- [ ] Create route to new page
- [ ] Layout structure of music player
- [ ] Automatically detect the current service the user is streaming from
- [ ] Display the respective information from the section above
- [ ] Add pause/play functionality
- [ ] Add the ability to skip to the previous/next track
- [ ] Add the ability to shuffle the current queue
- [ ] Add the ability to repeat the current track/queue 
- [ ] Add the ability to view the current queue
- [ ] Add the ability to scrub through the current track using the progress bar
- [ ] Add the ability to skip to a specific lyric in the song by clicking on the lyric
- [ ] Add the ability to save the currently playing track to the user's current service library
- [ ] Add the ability to start a group listening session with other users
