### ISSUE TITLE
Remove Secret Key from `encryption.ts` and `decryption.ts`

### ISSUE THREAD

**Issue by ItsCentric** [ItsCentric/music-wizard#6]
Currently, the secret key used for encrypting and decrypting passwords is out in the open. This is not ideal. Instead, the secret key should be stored in an environment variable and then used in those files to keep the secret key secret.

### Tasks

- [x] Remove the `key` variable from both files
- [x] Create an environment variable for the secret key in `.env`
- [x] Generate a new secret key using the `crypto` library
