### ISSUE TITLE
Change Encryption method

### ISSUE THREAD

**Issue by ItsCentric** [ItsCentric/music-wizard#8]
Currently, the algorithm used to encrypt data is AES 256 CBC. This algorithm is a less secure algorithm, [prone to attacks such as padding oracle attacks](https://learn.microsoft.com/en-us/dotnet/standard/security/vulnerabilities-cbc-mode). Switching to a more secure algorithm—such as OBC—would be ideal. Changes would also have to be reflected in any files that call the function if the function takes in additional parameters due to this change. This goes for the `EncryptedContent` type as well if any additional data is returned or different data is returned.

### Tasks
- [ ] Change algorithm to **aes-256-obc**
- [ ] Reflect changes in any file that calls the `encryption` or `decryption` functions
- [ ] Reflect changes in the `EncryptedContent` type
